export const personalInfo = {
  name: "Hemlata Dewangan",
  firstName: "Hemlata",
  lastName: "Dewangan",
  title: "Full Stack Web Developer",
  tagline: "Crafting Digital Experiences\nWith Precision & Elegance",
  email: "hemlata.dewangan@email.com",
  phone: "+91 98765 43210",
  location: "Indore, Madhya Pradesh, India",
  github: "https://github.com/hemlatadewangan",
  linkedin: "https://linkedin.com/in/hemlatadewangan",
  twitter: "https://twitter.com/hemlatadewangan",
  resume: "/resume.pdf",
  bio: "Passionate full-stack developer with 3+ years of experience building scalable web applications. I specialize in creating seamless digital experiences from concept to deployment.",
  yearsExperience: "3+",
  projectsCompleted: "50+",
  happyClients: "30+",
  techStack: "20+",
};

export const roles = [
  "Full Stack Developer",
  "React Specialist",
  "Next.js Expert",
  "Node.js Developer",
  "UI/UX Enthusiast",
];

export const skills = {
  frontend: [
    { name: "React.js", level: 92 },
    { name: "Next.js", level: 88 },
    { name: "TypeScript", level: 85 },
    { name: "Tailwind CSS", level: 90 },
    { name: "Framer Motion", level: 78 },
    { name: "Redux", level: 80 },
  ],
  backend: [
    { name: "Node.js", level: 87 },
    { name: "Express.js", level: 85 },
    { name: "PostgreSQL", level: 80 },
    { name: "MongoDB", level: 82 },
    { name: "REST APIs", level: 90 },
    { name: "GraphQL", level: 72 },
  ],
  tools: [
    { name: "Git & GitHub", level: 90 },
    { name: "Docker", level: 75 },
    { name: "AWS", level: 70 },
    { name: "Figma", level: 78 },
    { name: "Prisma ORM", level: 82 },
    { name: "Jest", level: 76 },
  ],
};

export const techMarquee = [
  "React.js", "Next.js", "TypeScript", "Node.js", "PostgreSQL",
  "MongoDB", "GraphQL", "Docker", "AWS", "Tailwind CSS",
  "Express.js", "Redux", "Prisma", "Jest", "Figma",
];

export const projects = [
  {
    id: 1,
    title: "ShopSphere",
    category: "Full Stack",
    description: "A full-featured e-commerce platform with real-time inventory management, payment integration, and an admin dashboard.",
    longDescription: "Built with Next.js 14, TypeScript, PostgreSQL, and Stripe integration. Features include product search, filtering, cart management, and order tracking.",
    tags: ["Next.js", "TypeScript", "PostgreSQL", "Stripe", "Tailwind"],
    github: "#",
    live: "#",
    featured: true,
    year: "2024",
  },
  {
    id: 2,
    title: "TaskFlow Pro",
    category: "Full Stack",
    description: "A collaborative project management tool with real-time updates, drag-and-drop kanban boards, and team collaboration features.",
    longDescription: "Developed using React, Node.js, Socket.io, and MongoDB. Supports real-time collaboration, file uploads, and deadline tracking.",
    tags: ["React", "Node.js", "Socket.io", "MongoDB", "Redux"],
    github: "#",
    live: "#",
    featured: true,
    year: "2024",
  },
  {
    id: 3,
    title: "DevBlog CMS",
    category: "Frontend",
    description: "A headless CMS-powered developer blog with MDX support, syntax highlighting, and SEO optimization.",
    longDescription: "Built with Next.js, MDX, and a custom CMS. Features dark/light mode, reading progress, and newsletter subscription.",
    tags: ["Next.js", "MDX", "Contentful", "GraphQL"],
    github: "#",
    live: "#",
    featured: false,
    year: "2023",
  },
  {
    id: 4,
    title: "FinTrack API",
    category: "Backend",
    description: "A RESTful API for personal finance tracking with expense categories, budgeting, and analytics endpoints.",
    longDescription: "Node.js/Express API with PostgreSQL database, JWT auth, Redis caching, and comprehensive Swagger documentation.",
    tags: ["Node.js", "Express", "PostgreSQL", "Redis", "Swagger"],
    github: "#",
    live: "#",
    featured: false,
    year: "2023",
  },
  {
    id: 5,
    title: "WeatherVue",
    category: "Frontend",
    description: "A beautiful weather dashboard with animated visualizations, 7-day forecasts, and location-based data.",
    longDescription: "React app using OpenWeatherMap API with interactive charts, geolocation support, and PWA capabilities.",
    tags: ["React", "Chart.js", "OpenWeatherMap", "PWA"],
    github: "#",
    live: "#",
    featured: false,
    year: "2022",
  },
  {
    id: 6,
    title: "AuthGuard",
    category: "Library",
    description: "A reusable authentication library with JWT, OAuth2, 2FA support, and role-based access control.",
    longDescription: "Open-source npm package with comprehensive documentation, supporting multiple auth strategies and session management.",
    tags: ["Node.js", "JWT", "OAuth2", "npm"],
    github: "#",
    live: "#",
    featured: false,
    year: "2022",
  },
];

export const experiences = [
  {
    id: 1,
    role: "Full Stack Developer",
    company: "TechNova Solutions",
    location: "Indore, India",
    period: "Jan 2023 – Present",
    type: "Full-time",
    description: "Lead developer for client-facing web applications. Built and maintained 10+ production apps using React, Next.js, and Node.js. Reduced page load time by 40% through performance optimizations.",
    highlights: [
      "Architected a microservices backend serving 100k+ daily requests",
      "Mentored 3 junior developers and conducted weekly code reviews",
      "Integrated third-party APIs including Stripe, Twilio, and AWS S3",
      "Achieved 99.9% uptime through robust error handling and monitoring",
    ],
  },
  {
    id: 2,
    role: "Frontend Developer Intern",
    company: "Pixel Craft Agency",
    location: "Bhopal, India",
    period: "Jun 2022 – Dec 2022",
    type: "Internship",
    description: "Developed responsive UI components and interactive dashboards. Collaborated with design team to implement pixel-perfect interfaces.",
    highlights: [
      "Built a 20+ component React library used across multiple projects",
      "Improved mobile performance scores from 60 to 92 (Lighthouse)",
      "Implemented WCAG 2.1 AA accessibility standards",
    ],
  },
  {
    id: 3,
    role: "Freelance Web Developer",
    company: "Self-Employed",
    location: "Remote",
    period: "2021 – 2022",
    type: "Freelance",
    description: "Delivered custom web solutions for 15+ clients across diverse industries including retail, education, and healthcare.",
    highlights: [
      "Built 15+ client websites from scoping to production deployment",
      "Managed full project lifecycle independently",
      "Maintained consistent 5-star client satisfaction rating",
    ],
  },
];

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "Contact", href: "#contact" },
];
